"""Tests for compiler and credentials features."""

import pytest


class TestPythonCompiler:
    """Test Python compiler."""

    def test_compile_simple_workflow(self):
        from app.core.compiler import PythonCompiler
        from app.core.workflow_definition import WorkflowDefinition, WorkflowNode, WorkflowEdge, NodeType

        definition = WorkflowDefinition(
            nodes=[
                WorkflowNode(id="n1", node_type=NodeType.TRIGGER, config={}),
                WorkflowNode(id="n2", node_type=NodeType.OUTPUT, config={"destination": "log"}),
            ],
            edges=[
                WorkflowEdge(id="e1", source_node_id="n1", target_node_id="n2"),
            ],
        )

        compiler = PythonCompiler()
        code = compiler.compile(definition, "Test Workflow")

        assert "async def execute_workflow" in code
        assert "NODES" in code
        assert '"n1"' in code
        assert '"n2"' in code
        assert "# Generated by FlowAlchemy" in code

    def test_compile_http_request_node(self):
        from app.core.compiler import PythonCompiler
        from app.core.workflow_definition import WorkflowDefinition, WorkflowNode, NodeType

        definition = WorkflowDefinition(
            nodes=[
                WorkflowNode(
                    id="n1",
                    node_type=NodeType.HTTP_REQUEST,
                    config={"url": "https://api.example.com", "method": "GET"},
                ),
            ],
            edges=[],
        )

        compiler = PythonCompiler()
        code = compiler.compile(definition, "HTTP Test")

        assert "httpx" in code
        assert "https://api.example.com" in code

    def test_compile_preserves_config(self):
        from app.core.compiler import PythonCompiler
        from app.core.workflow_definition import WorkflowDefinition, WorkflowNode, NodeType

        definition = WorkflowDefinition(
            nodes=[
                WorkflowNode(
                    id="n1",
                    node_type=NodeType.DELAY,
                    config={"seconds": 5},
                ),
            ],
            edges=[],
        )

        compiler = PythonCompiler()
        code = compiler.compile(definition, "Delay Test")

        assert '"seconds": 5' in code


class TestEncryptionService:
    """Test encryption service."""

    def test_encrypt_decrypt(self):
        from app.core.encryption import encrypt_value, decrypt_value

        plaintext = "my-secret-api-key-12345"
        encrypted = encrypt_value(plaintext)
        decrypted = decrypt_value(encrypted)

        assert decrypted == plaintext
        assert encrypted != plaintext

    def test_encrypt_different_each_time(self):
        from app.core.encryption import encrypt_value, decrypt_value

        plaintext = "same-secret"
        enc1 = encrypt_value(plaintext)
        enc2 = encrypt_value(plaintext)

        # Fernet uses timestamp, so ciphertexts differ
        # But both decrypt to same value
        assert decrypt_value(enc1) == plaintext
        assert decrypt_value(enc2) == plaintext

    def test_decrypt_invalid_ciphertext(self):
        from app.core.encryption import decrypt_value

        with pytest.raises(Exception):
            decrypt_value("invalid-ciphertext")


class TestCredentialAPI:
    """Test credential API endpoints."""

    def test_create_credential(self, client, auth_headers):
        response = client.post(
            "/api/credentials",
            headers=auth_headers,
            json={
                "name": "Test API Key",
                "credential_type": "api_key",
                "value": "sk-test-12345",
            },
        )
        assert response.status_code == 201
        data = response.json()
        assert data["name"] == "Test API Key"
        assert data["credential_type"] == "api_key"

    def test_list_credentials(self, client, auth_headers):
        # Create one first
        client.post(
            "/api/credentials",
            headers=auth_headers,
            json={
                "name": "Test",
                "credential_type": "api_key",
                "value": "key123",
            },
        )

        response = client.get("/api/credentials", headers=auth_headers)
        assert response.status_code == 200
        assert len(response.json()) >= 1

    def test_get_credential(self, client, auth_headers):
        create_resp = client.post(
            "/api/credentials",
            headers=auth_headers,
            json={
                "name": "Get Test",
                "credential_type": "token",
                "value": "tok-xyz",
            },
        )
        cred_id = create_resp.json()["id"]

        response = client.get(f"/api/credentials/{cred_id}", headers=auth_headers)
        assert response.status_code == 200
        assert response.json()["name"] == "Get Test"

    def test_delete_credential(self, client, auth_headers):
        create_resp = client.post(
            "/api/credentials",
            headers=auth_headers,
            json={
                "name": "Delete Me",
                "credential_type": "password",
                "value": "pass123",
            },
        )
        cred_id = create_resp.json()["id"]

        response = client.delete(f"/api/credentials/{cred_id}", headers=auth_headers)
        assert response.status_code == 204

    def test_unauthorized_credential_access(self, client, auth_headers):
        # Create credential
        create_resp = client.post(
            "/api/credentials",
            headers=auth_headers,
            json={
                "name": "Private",
                "credential_type": "api_key",
                "value": "secret",
            },
        )

        # Try to access without auth
        response = client.get("/api/credentials")
        assert response.status_code in [401, 403]
