"""add api_key_hash and api_key_prefix

Revision ID: 52bb2dd9f3f5
Revises: 434821f2c40d
Create Date: 2026-09-14 16:38:04.716390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bb2dd9f3f5'
down_revision: Union[str, None] = '434821f2c40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('api_key_prefix', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['api_key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'api_key_prefix')
    op.drop_column('users', 'api_key_hash')
    # ### end Alembic commands ###
