"""drop_plaintext_api_key_column

Revision ID: b9e1fdb6f482
Revises: 52bb2dd9f3f5
Create Date: 2026-09-15 10:36:19.655740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e1fdb6f482'
down_revision: Union[str, None] = '52bb2dd9f3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_api_key_key', 'users', type_='unique')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_api_key_key', 'users', ['api_key'])
    # ### end Alembic commands ###
