"""Python Code Compiler — generates standalone Python scripts from workflows."""

import re
import json
from typing import Dict, Any, List
from app.core.workflow_definition import WorkflowDefinition, WorkflowNode, NodeType


def _sanitize_name(name: str) -> str:
    """Sanitize workflow name for use in code."""
    return re.sub(r'[^\w\-.]', '_', name)[:100]


def _escape_string(s: str) -> str:
    """Escape string for safe interpolation in code."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')


class PythonCompiler:
    """Compiles workflow definitions to standalone Python scripts."""

    def compile(self, definition: WorkflowDefinition, workflow_name: str) -> str:
        """Generate a standalone Python script from a workflow definition."""
        safe_name = _sanitize_name(workflow_name)
        escaped_name = _escape_string(workflow_name)

        lines = []
        lines.append(self._header(safe_name, escaped_name))
        lines.append(self._imports())
        lines.append(self._node_definitions(definition))
        lines.append(self._url_validator())
        lines.append(self._execute_function(definition))
        lines.append(self._main_block(safe_name))

        return "\n".join(lines)

    def _header(self, safe_name: str, escaped_name: str) -> str:
        return "#!/usr/bin/env python3\n# Generated by FlowAlchemy — " + escaped_name + "\n# WARNING: This is auto-generated code. Review before running."

    def _imports(self) -> str:
        return """
import httpx
import json
import asyncio
from datetime import datetime
from typing import Any, Dict, Optional
from urllib.parse import urlparse
import ipaddress
import socket


BLOCKED_NETWORKS = [
    ipaddress.ip_network("127.0.0.0/8"),
    ipaddress.ip_network("10.0.0.0/8"),
    ipaddress.ip_network("172.16.0.0/12"),
    ipaddress.ip_network("192.168.0.0/16"),
    ipaddress.ip_network("169.254.0.0/16"),
    ipaddress.ip_network("100.64.0.0/10"),
    ipaddress.ip_network("0.0.0.0/32"),
    ipaddress.ip_network("::1/128"),
    ipaddress.ip_network("fc00::/7"),
    ipaddress.ip_network("fe80::/10"),
]

BLOCKED_HOSTS = frozenset({
    "localhost", "127.0.0.1", "0.0.0.0", "[::1]",
    "metadata.google.internal", "169.254.169.254",
})


def _is_safe_url(url: str) -> bool:
    \"\"\"Check if URL is safe (not targeting private/internal IPs).\"\"\"
    try:
        parsed = urlparse(url)
        if parsed.scheme not in ("http", "https"):
            return False

        hostname = parsed.hostname
        if not hostname:
            return False

        if hostname.lower() in BLOCKED_HOSTS:
            return False

        try:
            resolved_ip = ipaddress.ip_address(socket.gethostbyname(hostname))
            for network in BLOCKED_NETWORKS:
                if resolved_ip in network:
                    return False
        except socket.gaierror:
            return False

        return True
    except Exception:
        return False"""


    def _node_definitions(self, definition: WorkflowDefinition) -> str:
        lines = ['\n# Node definitions']
        lines.append("NODES = {")
        for node in definition.nodes:
            config_str = json.dumps(node.config, indent=4)
            lines.append(f'    "{node.id}": {{')
            lines.append(f'        "type": "{node.node_type.value}",')
            lines.append(f'        "config": {config_str},')
            lines.append("    },")
        lines.append("}")
        return "\n".join(lines)

    def _url_validator(self) -> str:
        return """

def _validate_url(url: str) -> str:
    \"\"\"Validate URL and raise if unsafe.\"\"\"
    if not _is_safe_url(url):
        raise ValueError(f"URL not allowed (private/internal IP): {url}")
    return url"""

    def _execute_function(self, definition: WorkflowDefinition) -> str:
        lines = ['\nasync def execute_node(node_id: str, config: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:']
        lines.append('    """Execute a single node."""')
        lines.append('    node_type = config["type"]')
        lines.append('    node_config = config["config"]')
        lines.append("")
        lines.append('    if node_type == "trigger":')
        lines.append("        return {")
        lines.append('            "trigger_data": context.get("trigger_data", {}),')
        lines.append('            "timestamp": datetime.utcnow().isoformat(),')
        lines.append("        }")
        lines.append("")
        lines.append('    elif node_type == "http_request":')
        lines.append("        url = _validate_url(node_config.get('url', ''))")
        lines.append("        method = node_config.get('method', 'GET').upper()")
        lines.append("        headers = node_config.get('headers', {})")
        lines.append("        body = node_config.get('body')")
        lines.append("")
        lines.append("        async with httpx.AsyncClient(timeout=30.0, follow_redirects=False) as client:")
        lines.append("            if method == 'GET':")
        lines.append("                response = await client.get(url, headers=headers)")
        lines.append("            elif method == 'POST':")
        lines.append("                response = await client.post(url, headers=headers, json=body)")
        lines.append("            elif method == 'PUT':")
        lines.append("                response = await client.put(url, headers=headers, json=body)")
        lines.append("            elif method == 'DELETE':")
        lines.append("                response = await client.delete(url, headers=headers)")
        lines.append("            else:")
        lines.append("                raise ValueError(f'Unsupported HTTP method: {method}')")
        lines.append("")
        lines.append("            return {")
        lines.append('                "status_code": response.status_code,')
        lines.append('                "headers": dict(response.headers),')
        lines.append('                "body": response.text,')
        lines.append("            }")
        lines.append("")
        lines.append('    elif node_type == "transform":')
        lines.append("        operation = node_config.get('operation', 'identity')")
        lines.append("        input_data = context.get('input', {})")
        lines.append("")
        lines.append("        if operation == 'identity':")
        lines.append("            return input_data")
        lines.append("        elif operation == 'json_path':")
        lines.append("            path = node_config.get('path', '')")
        lines.append("            result = input_data")
        lines.append("            for key in path.split('.'):")
        lines.append("                if key:")
        lines.append("                    result = result.get(key, {})")
        lines.append("            return result")
        lines.append("        elif operation == 'merge':")
        lines.append("            sources = node_config.get('sources', [])")
        lines.append("            merged = {}")
        lines.append("            for source in sources:")
        lines.append("                merged.update(context.get(source, {}))")
        lines.append("            return merged")
        lines.append("        else:")
        lines.append("            return input_data")
        lines.append("")
        lines.append('    elif node_type == "condition":')
        lines.append("        # Safe condition evaluation - only allows simple comparisons")
        lines.append("        condition = node_config.get('condition', 'true')")
        lines.append("        # For safety, conditions must be simple boolean expressions")
        lines.append("        # Use basic keyword arguments instead of eval")
        lines.append("        result = condition.lower() in ('true', 'yes', '1', 'on')")
        lines.append('        return {"result": result}')
        lines.append("")
        lines.append('    elif node_type == "delay":')
        lines.append("        seconds = node_config.get('seconds', 1)")
        lines.append("        await asyncio.sleep(seconds)")
        lines.append('        return {"delayed": seconds}')
        lines.append("")
        lines.append('    elif node_type == "output":')
        lines.append("        destination = node_config.get('destination', 'log')")
        lines.append("        data = context.get('input', {})")
        lines.append('        if destination == "log":')
        lines.append('            print(json.dumps(data, indent=2))')
        lines.append("        return {")
        lines.append('            "destination": destination,')
        lines.append('            "data": data,')
        lines.append("        }")
        lines.append("")
        lines.append('    else:')
        lines.append("        raise ValueError(f'Unknown node type: {node_type}')")
        lines.append("")
        return "\n".join(lines)

    def _main_block(self, name: str) -> str:
        return f"""
async def execute_workflow(trigger_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    \"\"\"Execute the complete workflow.\"\"\"
    context = {{"trigger_data": trigger_data or {{}}}}

    # Build execution order from edges
    execution_order = _build_execution_order()

    for node_ids in execution_order:
        tasks = []
        for node_id in node_ids:
            node_config = NODES[node_id]
            tasks.append(execute_node(node_id, node_config, context))

        results = await asyncio.gather(*tasks)

        for node_id, result in zip(node_ids, results):
            context[node_id] = result
            context["input"] = result

    return context


def _build_execution_order() -> List[List[str]]:
    \"\"\"Build topological execution order.\"\"\"
    # Simple topological sort
    in_degree = {{node_id: 0 for node_id in NODES}}
    edges = []

    # Parse edges from node configs (simplified)
    for node_id, config in NODES.items():
        if "source" in config:
            edges.append((config["source"], node_id))
            in_degree[node_id] += 1

    # BFS topological sort
    queue = [node_id for node_id, degree in in_degree.items() if degree == 0]
    order = []

    while queue:
        level = []
        next_queue = []
        for node_id in queue:
            level.append(node_id)
            for src, tgt in edges:
                if src == node_id:
                    in_degree[tgt] -= 1
                    if in_degree[tgt] == 0:
                        next_queue.append(tgt)
        order.append(level)
        queue = next_queue

    return order


if __name__ == "__main__":
    result = asyncio.run(execute_workflow({{"key": "value"}}))
    print("\\n=== {name} Result ===")
    print(json.dumps(result, indent=2, default=str))
"""
